"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-05 11:28:24.762398
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("body_part", sa.Text(), nullable=False),
        sa.Column("camera_view", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.CheckConstraint("camera_view IN ('side', 'front')", name="ck_exercises_camera_view"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_reps", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("good_reps", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("avg_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sessions_user_started", "sessions", ["user_id", "started_at"], unique=False)
    op.create_table(
        "reps",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("rep_index", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("min_angle", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("max_angle", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "errors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint("duration_ms >= 0", name="ck_reps_duration"),
        sa.CheckConstraint(
            "min_angle BETWEEN 0 AND 180 AND max_angle BETWEEN 0 AND 180", name="ck_reps_angles"
        ),
        sa.CheckConstraint("rep_index >= 1", name="ck_reps_rep_index"),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name="ck_reps_score"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "rep_index", name="uq_reps_session_rep_index"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reps")
    op.drop_index("ix_sessions_user_started", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("users")
    op.drop_table("exercises")
    # ### end Alembic commands ###
