"""every attempt: counted flag, miss reason, set aggregates

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 13:31:09.980175
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reps", sa.Column("counted", sa.Boolean(), server_default=sa.text("true"), nullable=False)
    )
    op.add_column("reps", sa.Column("miss_reason", sa.Text(), nullable=True))
    op.add_column(
        "sessions", sa.Column("counted_avg_score", sa.Numeric(precision=5, scale=2), nullable=True)
    )
    op.add_column(
        "sessions", sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False)
    )
    op.add_column(
        "sessions",
        sa.Column("missed_reps", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "sessions",
        sa.Column("unseen_reps", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_reps_miss",
        "reps",
        "(counted AND miss_reason IS NULL) OR (NOT counted AND miss_reason IN "
        "('partial', 'too_short', 'too_long', 'lost_tracking') AND score = 0)",
    )
    # Backfill: every rep stored before this migration was a counted rep.
    op.execute("UPDATE sessions SET attempts = total_reps, counted_avg_score = avg_score")


def downgrade() -> None:
    # Missed attempts can't be represented in the old schema.
    op.execute("DELETE FROM reps WHERE NOT counted")
    op.drop_constraint("ck_reps_miss", "reps", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "unseen_reps")
    op.drop_column("sessions", "missed_reps")
    op.drop_column("sessions", "attempts")
    op.drop_column("sessions", "counted_avg_score")
    op.drop_column("reps", "miss_reason")
    op.drop_column("reps", "counted")
    # ### end Alembic commands ###
